//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTEMEMBRESIA
    {
        public int ID_CLIENTEMEMBRESIA { get; set; }
        public int ID_MEMBRESIA { get; set; }
        public string ID_USU { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual MEMBRESIA MEMBRESIA { get; set; }
    }
}
