//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBRESIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBRESIA()
        {
            this.CLIENTEMEMBRESIA = new HashSet<CLIENTEMEMBRESIA>();
        }
    
        public int ID_MEMBRESIA { get; set; }
        public string DES_MEN { get; set; }
        public decimal PRE_MEN { get; set; }
        public string CAR_MEM { get; set; }
        public Nullable<int> DIAS_MEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTEMEMBRESIA> CLIENTEMEMBRESIA { get; set; }
    }
}
