//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DEPARTAMENTO()
        {
            this.TB_CONTACTO = new HashSet<TB_CONTACTO>();
        }
    
        public int COD_DEP { get; set; }
        public string NOM_DEP { get; set; }
        public int TIP_DEP { get; set; }
        public int NRO_PISO { get; set; }
        public int NUM_HABITACIONES { get; set; }
        public decimal PRECIO { get; set; }
        public byte[] FOTO { get; set; }
        public int DISTRITO { get; set; }
        public string ID { get; set; }
        public string DIR_DEP { get; set; }
        public string DES_DEP { get; set; }
        public string SERV_DEP { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CONTACTO> TB_CONTACTO { get; set; }
        public virtual TB_DISTRITO TB_DISTRITO { get; set; }
        public virtual TB_TIPODEPARTAMENTO TB_TIPODEPARTAMENTO { get; set; }
    }
}
