//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_PITEntities : DbContext
    {
        public BD_PITEntities()
            : base("name=BD_PITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_CONTACTO> TB_CONTACTO { get; set; }
        public virtual DbSet<TB_DEPARTAMENTO> TB_DEPARTAMENTO { get; set; }
        public virtual DbSet<TB_DISTRITO> TB_DISTRITO { get; set; }
        public virtual DbSet<TB_TIPODEPARTAMENTO> TB_TIPODEPARTAMENTO { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
