//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTACTO
    {
        public int COD_CON { get; set; }
        public string COD_DEMA { get; set; }
        public string COD_OFER { get; set; }
        public string NOM_CON { get; set; }
        public string EMAIL_CON { get; set; }
        public string TEL_CON { get; set; }
        public string TEXT_CON { get; set; }
        public string ESTADO { get; set; }
        public int COD_DEP { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TB_DEPARTAMENTO TB_DEPARTAMENTO { get; set; }
    }
}
