//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPARTAMENTO
    {
        public int COD_DEP { get; set; }
        public string NOM_DEP { get; set; }
        public int TIP_DEP { get; set; }
        public int NRO_PISO { get; set; }
        public int NUM_HABITACIONES { get; set; }
        public decimal PRECIO { get; set; }
        public byte[] FOTO { get; set; }
        public int DISTRITO { get; set; }
        public string ID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TB_DISTRITO TB_DISTRITO { get; set; }
        public virtual TB_TIPODEPARTAMENTO TB_TIPODEPARTAMENTO { get; set; }
    }
}
